spring:
  datasource:
      url: jdbc:mysql://192.168.1.254:3306/demo?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 1000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 192.168.1.254
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: 192.168.1.10
    port: 5672
    username: springcloud
    password: 123456
ftp:
  client:
    host: 192.168.1.10
    port: 21
    username: ftp01
    password: 123456
    encoding: utf-8
    passiveMode: false
    connectTimeout: 6000
    keepAliveTimeout: 30  
projectName: spring-cloud
webSite: http://spring.io
version: v1.0
#是否不允许刷新主页，不允许情况下，刷新主页会导致重新登录
notAllowRefreshIndex: false
#是否允许多账号同时登录
multiAccountLogin: true
defaultPassword: 123456
dbName: mysql
projectPath: D:\workspace_learn\spring-cloud
basePackageName: com.sapit.springcloud
weixin:
  appId: wx68401b35ef847057
  appSecret: f8cb21832a4bc571fcfbc53fa27d332c
  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  menu_create_url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  jssdk_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
  user_list_url: https://api.weixin.qq.com/cgi-bin/user/get?access_token=ACCESS_TOKEN&lang=zh_CN
  user_info_url: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
  user_openid_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
  getMedia: https://api.weixin.qq.com/cgi-bin/media/get